# Generated by Django 4.2.7 on 2026-02-26 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', '연차'), ('HALF', '반차'), ('SICK', '병가'), ('SPECIAL', '특별휴가')], max_length=10, verbose_name='휴가종류')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('reason', models.TextField(blank=True, verbose_name='사유')),
                ('status', models.CharField(choices=[('PENDING', '신청'), ('APPROVED', '승인'), ('REJECTED', '반려')], default='PENDING', max_length=10, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('reject_reason', models.TextField(blank=True, verbose_name='반려사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaves', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '휴가 신청',
                'verbose_name_plural': '휴가 신청 목록',
                'db_table': 'attendance_leave',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='근무일')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='출근시각')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='퇴근시각')),
                ('work_minutes', models.PositiveIntegerField(default=0, verbose_name='실근무분')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='초과근무분')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '출퇴근 기록',
                'verbose_name_plural': '출퇴근 기록 목록',
                'db_table': 'attendance_record',
                'ordering': ['-work_date'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
