# Generated by Django 4.2.7 on 2026-02-26 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='급여연도')),
                ('month', models.PositiveSmallIntegerField(verbose_name='급여월')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='기본급')),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='식대')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='교통비')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='초과근무수당')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총지급액')),
                ('national_pension', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='국민연금')),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='건강보험')),
                ('long_term_care', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='장기요양보험')),
                ('employment_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='고용보험')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='소득세')),
                ('local_income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='지방소득세')),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총공제액')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='실수령액')),
                ('overtime_minutes', models.PositiveIntegerField(default=0, verbose_name='월 초과근무(분)')),
                ('status', models.CharField(choices=[('DRAFT', '초안'), ('CONFIRMED', '확정')], default='DRAFT', max_length=10, verbose_name='상태')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='확정일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='확정자')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'db_table': 'payroll_record',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
