# Generated by Django 4.2.7 on 2026-02-25 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='부서명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='부서코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='직급명')),
                ('level', models.PositiveSmallIntegerField(help_text='1(사원) ~ 10(대표이사)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='직급레벨')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees_position',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=20, unique=True, verbose_name='사번')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('resident_no', models.CharField(blank=True, max_length=255, verbose_name='주민등록번호')),
                ('hire_date', models.DateField(verbose_name='입사일')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='기본급')),
                ('is_active', models.BooleanField(default=True, verbose_name='재직여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='부서')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position', verbose_name='직급')),
            ],
            options={
                'db_table': 'employees_employee',
                'ordering': ['employee_no'],
            },
        ),
    ]
